name = "RowMajorArrays"
uuid = "6bafa52e-5f81-47e0-b04a-bdb2c22449b4"
authors = ["Benjamin Lungwitz <benj.lung@googlemail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
